nostalgic-css/NES.css

scss/base/generic.scss, scss/base/reboot.scss
Just a tiny change to remove the anti-aliasing from the font :)
Currently:
Without font-smoothing:
=> disable font-smoothing 

index.html
Fixes #28
This update gives text fields unique `id`s so that their `label`s can be appropriately associated with them.
Additionally, this PR also changes the examples of the `.container` class to **not** use `label`s as the first element, as `label`s were inappropriate for these markup patterns.  They have been replaced by paragraph elements.
=> update label instances

css/nes.css, scss/elements/buttons.scss
Double check my work, I'm new to these contributions...
This is meant to solve this issue #19
=> swapped primary and success button styling

README-jp.md, README.md, package.json
This PR updates the repo links. I updated it in the READMEs to point to the new org version of the repo, and updated the repo link in the `package.json` so that `semantic-release` will work correctly in CI.
=> Update repo links

.npmignore
closes #97 
No more css conflicts everybodyyy 🎉 🎉
=> remove and untrack css

scss/base/generic.scss
Closes #39 
Fixes https://github.com/nostalgic-css/NES.css/pull/44#issuecomment-445416611
|current|this PR|
|----|----|
|![pr](https://user-images.githubusercontent.com/5305599/49679806-730ada00-fad1-11e8-95c7-5dcff4abae57.gif)|![expect](https://user-images.githubusercontent.com/5305599/49679808-74d49d80-fad1-11e8-89f4-9f021f94157f.gif)|
=> fix: preserve outline0 for checkboxes and radios only

docs/textarea.stories.js, index.html, scss/form/inputs.scss
This PR is to set the HTML5 `<textarea>` the same style as the inputs. So I just added the textarea class to inputs and a new textarea storybook.
If the users are supposed to use the input class and not this new `textarea` class, **this PR must be rejected**. 
I just think it will be more intuitive to use this `textarea` class, and for future changes between inputs/textarea we could refactor and keep them in separate files.
=> feat(textarea): add textarea component

package.json
I've softened the `commitlint` rules. Commit subjects can now start with a capital letter and/or end with a full stop (.). 😉
=> Soften `commitlint` rules

scss/pixel-arts/bulbasaur.scss, scss/pixel-arts/charmander.scss, scss/pixel-arts/squirtle.scss
This three pokémons icons have the wrong width/height.
This PR is to fix it:
=> fix(icons): changed pokemons icons width and height

.github/README-es.md, .github/README-jp.md, .github/README-pt-BR.md, README.md
[This font](http://cactus.tistory.com/193) actually used for 80-90s PC and games in Korea.
Furthermore, it's used for gameboy, NES, DOS-like emulator to print out Korean.
So i thought this font fits for this framework, and can satisfy user's demand who wants to print some Korean.
=> add font recommendation for Korean in README.md

index.html
fix #196
Demo site has error that mixed content.
so I used `https` instead of `http`.
not include breaking.
**Caveats**
=> [#196] use https instead of http

package.json
I did a dumb. I changed the name of he script that updates the package headers before a release, but
I didn't tell `semantic-release-exec` that I'd changed it. 😬
=> fix: Fix the script that's run by `semantic-release`

package.json
We no longer need to build the entire framework to lint it, so I've removed the build step from the
pre-commit hook and replaced it with just stylelint.
=> perf: Speed up pre-commit hooks

index.html, scss/pixel-arts/_index.scss
This fix the position of the mario icon for the `index.html`
This will only work when we launch the next release
**Caveats**
To test, in `index.html` change this:
```html
<link href="https://unpkg.com/nes.css/css/nes.min.css" rel="stylesheet" />
```
to this:
```html
<link href="./css/nes.min.css" rel="stylesheet" />
```
And run the `npm run build`, then check `index.html` icons section.
For some reason the first icon imported after `octocat.scss` got bugged and moved to the upper-left corner, so for now I just moved the `octocat.scss` to the last import. So this is isn't really a major fix, but I will investigate more later.
=> Fix: mario icon on index.html and one line indent

docs/dialogs.stories.js, scss/elements/_index.scss, scss/elements/dialogs.scss
The dialog styles added by @sophi-est weren't being loaded into the compiled stylesheet. I've added
them to the elements index file and moved the rounded corners styles into and `.is-rounded` modifier
class.
This restores functionality that was lost, does not remove or break other functionality.
**Caveats**
The rounded corners for `<dialog />` components necessarily *are not* the same as `.container` components. This is because `<dialog />` elements are intended to be displayed over top of other elements and, with the way we create pixelated corners currently, the `<dialog />` component can't receive a background color.
**Testing Instructions**
1. Load Storybook (`npm run storybook`)
1. Verify that `<dialog />` components still work
1. Verify that the …
=> fix(dialog): Fix dialog corners

scss/elements/checkboxes.scss, scss/elements/lists.scss, scss/elements/radios.scss, scss/icons/icons.scss, scss/pixel-arts/ash.scss, scss/pixel-arts/bcrikko.scss, scss/pixel-arts/bulbasaur.scss, scss/pixel-arts/charmander.scss, scss/pixel-arts/kirby.scss, scss/pixel-arts/mario.scss, scss/pixel-arts/nes-icon.scss, scss/pixel-arts/nes-jp-icon.scss, scss/pixel-arts/octocat.scss, scss/pixel-arts/phone.scss, scss/pixel-arts/pokeball.scss, scss/pixel-arts/smartphone.scss, scss/pixel-arts/snes-icon.scss, scss/pixel-arts/snes-jp-icon.scss, scss/pixel-arts/squirtle.scss, scss/utilities/icon-mixin.scss
ref #205
This will greatly reduce the size of the compiled css files by not having to duplicate the `box-shadows` property for every size of each icon. This change makes it so everything about the icon is based off of the `font-size` property by using `em` units. A wonderful side effect is that now icons and pixel-art can be any size you want if you just change the font-size on the `.nes-icon` all the `.is-small` etc. classes do is adjust between predefined sizes. The width and hight is calculated according to the number of pixels in each dimension.
**Before:**
Build time: 0m31.281s
| Size | file |
| -----|-----|
| 633K | nes.css |
|  64K | nes.css.map |
| 602K | nes.min.css |
**After:**
Build Time: 0m25.455s
| Size | file |
| -----|-----|
| 255K | nes.css |
|  46K | …
=> perf: icon shadow optimization

docs/text.stories.js, scss/elements/_index.scss, scss/elements/text.scss
Fixes #226
This PR adds text colors like `is-primary` etc.
To use those colors the text element must also add the class `nes-text`.
It isn't breaking
=> feat(text colors): adds text colors classes like is-primary etc.

index.html, scss/elements/badges.scss
This PR is to add the badges component that was added here #216.
Nothing else should break and the container issue is addressed here #235.
**Caveats**
I had to make some changes inside `badges.scss` so please review it again. Unfortunately in the first PR I test with only one badge and not a lot of badges next to each other, so I had to make some changes. Now it should be fine, I test it in storybook and `index.html` that is the purpose here.
=> feat: add badges into index.html and some corrections to support it

scss/elements/balloons.scss, scss/elements/containers.scss, scss/elements/progress.scss, scss/form/selects.scss
This PR is to fix only the `with-title` bug at #235 
N/A
**Caveats**
One thing here, I notice that the containers in https://nostalgic-css.github.io/NES.css/ is more rounded than the ones in develop. Not sure if that was intended.
=> fix(container): removed padding-top inside with-title class

.github/README-es.md, .github/README-jp.md, .github/README-pt-BR.md, .github/README-zh-CN.md, README.md
I just fixed the link to Misaki font.
Because geocities.jp will shutdown soon.
N/A
**Caveats**
N/A
=> docs(readme): Fix link to misaki font

scss/form/inputs.scss, scss/utilities/rounded-corners-mixin.scss
border is broken when zooming in/out on chrome
fix #244
`border-image` using Inline SVG is broken when zooming in/out on chome.
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/22016005/52128079-21875300-261b-11e9-98f2-0d57a72acecc.png)|![2019-02-05 20 37 34](https://user-images.githubusercontent.com/5305599/52271032-e9b73d00-2985-11e9-9b89-ee09f5368161.png)|
N/A
**Caveats**
=> fix border bugs on chrome

docs/inputs.stories.js, scss/form/checkboxes.scss
We need to add styles when the checkbox is on dark mode, currently, the
checkbox is not visible at all if the container is dark.
Now we can to add the class `is-dark` to a `nes-checkbox` element.
**Caveats**
Not yet.
=> [#255] Dark mode for checkbox

docs/select.stories.js, docs/text.stories.js, scss/elements/text.scss
This PR adds `is-disabled` to `Text`, because it had in `text.stories.js` but it was doing nothing, and I put it in #278 :smile: 
N/A
**Caveats**
I've also changed the module name in storybooks from `Text` to `Texts` and from `Select` to `Selects`.
=> feat(text): added is-disabled to text. changed text to texts.

scss/elements/dialogs.scss
ref #281. 
This PR fix the `is-dark` dialog white border, because it don't have an `after` like the `Container` component.
Before this PR:
After this PR:
N/A
**Caveats**
N/A
=> fix(dialog): fix dialogs is-dark white border missing.

scss/base/variables.scss
It just makes all scss variables default so that they can be easily overridden in projects
It doesn't break anything, unless a project was overriding some variables without working and left there... they would actually work now.
**Caveats**
None I can think of
=> feat: make all variables default

scss/utilities/icon-mixin.scss
use `@supports (-moz-appearance: meterbar)` instead of `@-moz-document url-prefix()`
I fixed style for firefox.
https://bugzilla.mozilla.org/show_bug.cgi?id=1035091
not
**Caveats**
=> fix(icon-mixin.scss): fix style on firefox

scss/utilities/rounded-corners-mixin.scss
I've changed the property of the `border-image-repeat` to stretch this fixes the bug in safari, and fixes the sliced borders in firefox too (#273) 👍 
tested in:
Chrome: 72.0.3626.119
Safari: 12.0
Firefox: 65.0.1
=> [#301] Fix blurred borders in safari

scss/elements/buttons.scss
resolves #328 
Description
When used `.nes-btn` in a tag `a` in the `hover` is added a underline and color in the text.
=> fix: remove underline in hover and set color

scss/form/inputs.scss
Remove the input and textarea shadow on Iphone and Ipad.
iOS 10+
=> fix: remove input shadow on ios

scss/form/selects.scss, story/select.stories.js
This PR adds a `is-dark` class to `nes-select` and solves #334.
This should not break anything.
**Caveats**
N/A.
=> Add select is-dark class type like input component

scss/helpers/_index.scss, scss/helpers/pointer.scss, scss/nes.scss
This PR will add an easy way to access the custom cursor that this library uses by adding a `nes-pointer` class
It only adds a new class, so it should be fully compatible
**Caveats**
I added some new sccs files based on the suggested path found in issue #339
=> feat: add the new nes-cursor class

.storybook/webpack.config.js, package.json, scripts/getFileAsDataURI.js, scripts/scssFunctions.js, scss/base/variables.scss
I’ve added a SCSS function that, when passed a file path, will inject the file as a data URI. This
is super helpful since it ensures that the cursor images will always be available for the CSS. This
issue currently prevents the npm version of the library from being usable at all.
These data URIs should work all the way back to IE9.
=> refactor: convert local images to data URIs

docs/script.js
fix #336
This solves #336. Not sure if it's very well aligned though... :thinking: 
N/A
**Caveats**
**Selects:**
**Inputs:**
=> docs: add select and input is-dark to docs

scss/form/checkboxes.scss, scss/form/radios.scss
I updated radio and checkbox style in iOS.
`-webkit-appearance: none` seems not to work in iOS.
So I added `visibility: none;`
* checkbox
* radio
ref https://github.com/nostalgic-css/NES.css/issues/8
Thanks for your review 🙏
=> Fix radio and checkbox style in ios

docs/script.js, scss/elements/buttons.scss
fix #74
I splitted the style into `:hover` and `:focus`.
https://github.com/nostalgic-css/NES.css/issues/74#issuecomment-500655038
no
**Caveats**
no
=> Fix focus color of buttons

.gitignore, scss/form/inputs.scss, scss/form/selects.scss
This PR resolves the issue #322 in which form inputs are bleeding out of parent container. This problem is solved by **subtracting the width of both left and right borders from the total width of input element.**
The solution:
- Uses css `calc()` to calculate the width of form input classes (nes-input, nes-textarea, nes-select)
- Uses SCSS string interpolation to place variable `$border-size`'s value inside `calc()`
This PR is not breaking any compatibility.
close #322
=> String interpolation to calculate width of inputs. Fix #322

scss/elements/balloons.scss, story/balloons.stories.js
Implementation so balloons can now have `is-dark`
re #345
Exactly what it says on the tin, I have added the ability for balloons to be displayed in dark mode.
__Screen:__
Non-breaking, tis a small change. However I did add a mixin due to repeating scss.
**Caveats**
None
=> feat(component-balloons): Dark Mode - Balloons

package.json
Hi,
I think we should add the min version (e.g. LTS ) of the node engine for this package.
Best,
Alpha
=> UPT: add LTS version for node engine

story/buttons.stories.js
This adds a story for input type file, by adding a `select` type knob to buttons, that can be toggled by button and file.
None.
**Caveats**
None, the classes (`is-primary`, etc.) are working too.
The default type is `button`.
=> feat(buttons): add storybook for input type file
