nostalgic-css/NES.css

README-jp.md
README.md

I translated the original README in English as best as I could. I'll be waiting for feedback as I don't really know Japanese. I also updated the directory listing with symbols from `tree` and linked the two READMEs to each other with the links on top.
PS: I left the TODOs in Japanese, I don't think users would find them useful.

README English translation

---

README-jp.md
README.md

close #37 
I added 8bit-like font list.
Please add to list your recommended font if you have. 🙏

Add Recommended fonts list

---

css/nes.css
scss/form/inputs.scss

Fixes the success color on the input

Update input success color for both css and sass

---

README-jp.md
README.md

I added the Gitter badge to the `README` to help direct users to our chat room.
#57

docs(badges): add gitter badge

---

.gitignore
.storybook/addons.js
.storybook/config.js
commitlint.config.js
package-lock.json
package.json

I failed to merge... 😢 
so we couldn't commit...

Fix config files

---

package.json

fix: remove 'git add ./css' from precommit stage

---

index.html

Again, not sure what happened here. Maybe I make a mistake in the last commit and forgot to add index.html :cry: 
I'm sorry for this again. I will do my best not to make this mistakes again. :pray: 
Please check if this is ok, or maybe it's too big:

feat(table): add table is-dark is-bordered in index.html

---

.storybook/config.js
index.html
scss/elements/containers.scss

 storybook container is-dark font color

---

scss/form/inputs.scss

fix(inputs.scss): fix field responsive

---

.npmignore

This removes a lot of the unnecessary files from our npm package.

Slim down our npm package

---

docs/containers.stories.js
index.html
scss/elements/containers.scss

This address #178 . 
:warning:  **Minor** breaking change - class `is-center` changed to `is-centered`. :warning: 
**Index.html**
**Storybook**

Change is-center container class to is-centered

---

index.html

close #197 
* I changed reference of css file url.
* I changed repository url
not include breaking
**Caveats**

[#197] Change source url

---

.github/README-es.md
.github/README-jp.md
.github/README-pt-BR.md

The `CONTRIBUTING-md's` links were broken inside each translated file, so I fixed the path
N/A
**Caveats**
N/A

Fix contributing links in all of the readmes

---

docs/select.stories.js
index.html
scss/form/_index.scss
scss/form/select.scss
scss/form/selects.scss
style.css

Implement styles for the `<select />` element, along with `is-success`, `is-warning` and `is-error` states. Based on https://github.com/Divoolej/react-select-nes-css-theme. Solves #152.
No breaking changes, only an addition of a new feature.
**Caveats**
Tested on latest Chrome, Firefox and Safari.
Here is how it looks on the demo page:

Styles for the <select /> element

---

index.html

This PR only adds 4 `is-small` icons to `index.html` that was missing (Reddit, Whatsapp, Gmail and Linkedin).
N/A
**Caveats**
I've also added the star icons `is-small` that was missing as well:

feat(index.html): added reddit, whatsapp, gmail and linkedin is-small

---

scss/elements/buttons.scss

Should fix #240.
N/A
**Caveats**
N/A

fix(buttons): fix is-disabled button state being able to click

---

docs/dialogs.stories.js
docs/inputs.stories.js
scss/elements/dialogs.scss
scss/form/inputs.scss

add a ```is-dark``` modifier to inputs.
is not breaking.

adding is-dark modifier to input

---

docs/progress.stories.js
scss/elements/progress.scss

Adding ```is-rounded``` modifier to ```.nes-progress``` elements.
It's not breaking.

adding is-rounded to progess

---

.github/README-es.md
.github/README-jp.md
.github/README-pt-BR.md
.github/README-zh-CN.md
README.md
index.html

I changed url to latest version url in demo page and README.md

Change to latest version url

---

.github/README-es.md
.github/README-jp.md
.github/README-pt-BR.md
.github/README-zh-CN.md
README.md
index.html
scss/base/variables.scss

Release 2.0.0 (take two).

---

scss/base/variables.scss

- Fix the position of the pointer cursor hotspot
- Optional: Executed `npm audit fix` which changed some package version numbers from package-lock and remove the invalid scripts used as comments in package definition
It doesn't break anything
**Caveats**
Nope
**Reference**
https://drafts.csswg.org/css-ui-3/#cursor

Fix cursor hand

---

.github/README-zh-CN.md

fix(readme-zh-ch.md): fix chinese typo
或者按照如下方式简单引**人** -> 或者按照如下方式简单引**入**
Not breaking.
**Caveats**
Nope.

Fix a Chinese typo

---

docs/script.js
docs/style.css

ref #292 
I fixed contributors to fetch from github. 🚀 
not
**Caveats**

docs: fetch contributors

---

.github/README-es.md
.github/README-jp.md
.github/README-pt-BR.md
.github/README-zh-CN.md
README.md

ref #305 
I changed cdn link.
**Caveats**

docs(readme.md): update latest version

---

docs/script.js

to reach github api request limit.
so I fixed it not to use the github API.
**Caveats**

docs: fix github api

---

package-lock.json
package.json

Security Alerts
* fstream
* tar
I executed `npm audit fix`. 🚓 
no
**Caveats**
no

👮🏻‍♂️Security update

---

docs/script.js
scss/nes-core.scss
scss/nes.scss

I moved `helpers/_index.scss` from `nes.scss` to `nes-core.scss`.
`helpers` is an unreleased feature, so there are no breaking changes.
**Caveats**

refactor: move helper.scss

---

.github/README-es.md
.github/README-jp.md
.github/README-pt-BR.md
.github/README-zh-CN.md
README.md
docs/index.html
docs/script.js

Update the document v2.2.0

---

scss/elements/buttons.scss
scss/form/checkboxes.scss
scss/form/radios.scss
scss/utilities/_index.scss
scss/utilities/visually-hidden.scss

ref #350 
I created `visually-hidden` util reffering to [a11y-css-reset](https://github.com/mike-engel/a11y-css-reset/blob/master/a11y.css).
no
**Caveats**
no

Refactor visually hidden elements

---

.github/CONTRUBUTING-ru.md
.github/README-ru.md
CONTRIBUTING.md
README.md

Add Russian translation for part of documentation
No breaking changes
**Caveats**
No caveats

docs: add russian docs translation

---

.github/README-pt-BR.md

A minimal translation correction in the file <README.md>
From:
`sass` - caminho para nosso arquivo fronte Sass principal
To:
`sass` - caminho para nosso arquivo de código fonte principal Sass
**Caveats**

A minor translation correction

---

docs/script.js
scss/elements/buttons.scss

close #245
I recreated the PR for #245 referring to https://github.com/nostalgic-css/NES.css/pull/245#discussion_r279232232.
none
**Caveats**
none

Add input-file feature

---

scss/pixel-arts/ash.scss
scss/pixel-arts/bcrikko.scss
scss/pixel-arts/bulbasaur.scss
scss/pixel-arts/charmander.scss
scss/pixel-arts/kirby.scss
scss/pixel-arts/mario.scss
scss/pixel-arts/nes-icon.scss
scss/pixel-arts/nes-jp-icon.scss
scss/pixel-arts/octocat.scss
scss/pixel-arts/phone.scss
scss/pixel-arts/pokeball.scss
scss/pixel-arts/smartphone.scss
scss/pixel-arts/snes-icon.scss
scss/pixel-arts/snes-jp-icon.scss
scss/pixel-arts/squirtle.scss
scss/utilities/_index.scss
scss/utilities/fill-gaps.scss
scss/utilities/icon-mixin.scss

ref https://github.com/nostalgic-css/NES.css/pull/370#discussion_r335787656
I created `fill-gaps` in utilities.
none
**Caveats**
none

Refactor fill-gaps

---

.github/FUNDING.yml

I added a `FUNDING.yml` file to activate OSS activities.
[My GitHub Sponsors Link](https://github.com/sponsors/BcRikko)
None
**Caveats**
None

add funding file

---

docs/script.js

Adds the docs for #345 
NA
**Caveats**
NA

docs(baloons): added `is-dark` baloons to the docs

---

docs/script.js

This PR updates the contributors static array adding +5 new contributors.
N/A
**Caveats**
N/A

docs: update contributors array
